spring:
  datasource:
    url: jdbc:log4jdbc:h2:mem:test
    driver-class-name: net.sf.log4jdbc.sql.jdbcapi.DriverSpy
  jpa:
    show-sql: true
    properties:
      hibernate.format_sql: true
    hibernate:
      ddl-auto: create-drop
  h2:
    console.enabled: true
 